### ISSUE TITLE
Non-reproducible inference with same seed

### ISSUE THREAD

**Issue by brian6091** [brian6091/Dreambooth#2]
https://github.com/huggingface/diffusers/issues/902
https://github.com/huggingface/diffusers/pull/314
https://github.com/huggingface/diffusers/issues/612
https://github.com/huggingface/diffusers/issues/208
https://github.com/pcuenca/diffusers-examples/blob/main/notebooks/stable-diffusion-seeds.ipynb
https://pytorch.org/docs/stable/notes/randomness.html

**Comment by brian6091** [comment]
Solved by directly injecting latents

**Comment by brian6091** [comment]
Solved by directly injecting latents

**Comment by mecevit** [comment]
Hey @brian6091, how did you inject latents? Can you provide some details?

**Comment by brian6091** [comment]
Hi @mecevit,

I found the idea in this notebook:
https://github.com/pcuenca/diffusers-examples/blob/main/notebooks/stable-diffusion-seeds.ipynb

See particularly the section "Latents generation".
